services:
  db:
    container_name: mariadb-vms
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    ports: [ "3306:3306" ]
    volumes: [ db_data:/var/lib/mysql ]

volumes:
  db_data: